version: '3.4'
networks:
  net:
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - net
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        
  frontend:
    container_name: frontend
    build:
        context: ./frontend
        dockerfile: Dockerfile
    ports:
      - "6060:80"
    depends_on:
      - backend
    networks:
      - net

